### ISSUE TITLE
debug messages don't appear

### ISSUE THREAD

**Issue by rgeber** [vforgione/logging2#6]
Hi

I've set log level to `debug` and am using some `.debug` messages. However, none of these show up while everything "up to" `info` works just fine.

Tested this with the stdout and file handlers.

Version 0.1.2 with Python 3.7

cu
Roman

**Comment by vforgione** [comment]
Sorry for the super long delay. Can you please share the code where this isn't working?

**Comment by vforgione** [comment]
No reply. Closing. Reopen if/when you're down to chat about this. Again very sorry about the delay.
